estate/urls.py
from django.urls import path
from .views import (
    index,
    HouseListView,
    HouseDetailView,
    HouseCreateView,
    HouseUpdateView,
    HouseDeleteView,
    RealtorListView,
    RealtorDetailView,
    RealtorCreateView,
    RealtorUpdateView,
    RealtorDeleteView,
    AssignToHouseView
)

urlpatterns = [
    path("", index, name="index"),
    path("houses/", HouseListView.as_view(), name="house-list"),
    path("houses/<int:pk>/", HouseDetailView.as_view(), name="house-detail"),
    path("houses/create/", HouseCreateView.as_view(), name="house-create"),
    path("houses/<int:pk>/update/", HouseUpdateView.as_view(), name="house-update"),
    path("houses/<int:pk>/delete/", HouseDeleteView.as_view(), name="house-delete"),
    path("realtors/", RealtorListView.as_view(), name="realtor-list"),
    path("realtors/<int:pk>/", RealtorDetailView.as_view(), name="realtor-detail"),
    path("realtors/create/", RealtorCreateView.as_view(), name="realtor-create"),
    path("realtors/<int:pk>/update", RealtorUpdateView.as_view(), name="realtor-update"),
    path("realtors/<int:pk>/delete/", RealtorDeleteView.as_view(), name="realtor-delete"),
    path("houses/<int:pk>/assign/", AssignToHouseView.as_view(), name="house-assign"),
    path("houses/<int:pk>/remove/", AssignToHouseView.as_view(), name="house-remove"),
]

app_name = "estate"

real_estate_info/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("estate.urls", namespace="estate")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link" style="color: black; font-weight: 500">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link" style="color: #fff;
    background-color: black;
    border-color: black; border-radius: 7px; padding-inline: 10px">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link" style="color: black; font-weight: 500">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand" href=""><img src="{% static 'ico/house.png' %}" style="width: 70px"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 top-menu">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url "estate:index" %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "estate:house-list" %}">Catalog</a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="{% url "estate:realtor-list" %}">Realtors</a>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto mb-0 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#"><img   src="{% static "ico/user.png" %}" style="width: 40px"></a>
          <ul class="dropdown-menu" aria-labelledby="navbarSupportedContent">
            {% if user.is_authenticated %}
    <li class="dropdown-item">{{ user.get_username }}</li>
    <li><a class="dropdown-item" href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
  {% else %}
    <li><a class="dropdown-item" href="{% url 'login'%}?next={{request.path}}">Login</a></li>
  {% endif %}
          </ul>
        </li>
      </ul>

    </div>
  </div>
</nav>