estate/urls.py
from django.urls import path
from .views import (
    index,
    HouseListView,
    HouseDetailView,
    HouseCreateView,
    HouseUpdateView,
    HouseDeleteView,
    RealtorListView,
    RealtorDetailView,
    RealtorCreateView,
    RealtorUpdateView,
    RealtorDeleteView,
    AssignToHouseView
)

urlpatterns = [
    path("", index, name="index"),
    path("houses/", HouseListView.as_view(), name="house-list"),
    path("houses/<int:pk>/", HouseDetailView.as_view(), name="house-detail"),
    path("houses/create/", HouseCreateView.as_view(), name="house-create"),
    path("houses/<int:pk>/update/", HouseUpdateView.as_view(), name="house-update"),
    path("houses/<int:pk>/delete/", HouseDeleteView.as_view(), name="house-delete"),
    path("realtors/", RealtorListView.as_view(), name="realtor-list"),
    path("realtors/<int:pk>/", RealtorDetailView.as_view(), name="realtor-detail"),
    path("realtors/create/", RealtorCreateView.as_view(), name="realtor-create"),
    path("realtors/<int:pk>/update", RealtorUpdateView.as_view(), name="realtor-update"),
    path("realtors/<int:pk>/delete/", RealtorDeleteView.as_view(), name="realtor-delete"),
    path("houses/<int:pk>/assign/", AssignToHouseView.as_view(), name="house-assign"),
    path("houses/<int:pk>/remove/", AssignToHouseView.as_view(), name="house-remove"),
]

app_name = "estate"

real_estate_info/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("estate.urls", namespace="estate")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

estate/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Owner(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField(blank=True)
    phone_number = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Address(models.Model):
    street = models.CharField(max_length=255)
    number = models.IntegerField()
    city = models.CharField(max_length=255)
    postal_code = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f"{self.city}, {self.street} {self.number}"


class Realtor(AbstractUser):
    rating = models.DecimalField(max_digits=2, decimal_places=1, default=0.0, null=True, blank=True)
    class Meta:
        verbose_name = "realtor"
        verbose_name_plural = "realtors"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("estate:realtor-detail", kwargs={"pk": self.pk})


class House(models.Model):
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE, related_name="houses", blank=True, null=True)
    address = models.ForeignKey(Address, on_delete=models.CASCADE, related_name="houses")
    price = models.IntegerField(blank=False, null=False)
    area = models.IntegerField()
    num_of_bedrooms = models.IntegerField(blank=True, null=True)
    num_of_floors = models.IntegerField(blank=True, null=True)
    realtor = models.ManyToManyField(Realtor, related_name="houses")

    @property
    def price_per_area(self):
        if self.area != 0:
            return round(self.price / self.area)
        else:
            return None

    def __str__(self):
        return f"{self.price}, {str(self.owner)}"





estate/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from .models import Realtor


class HouseSearchForm(forms.Form):
    model = forms.CharField(max_length=255,
                            required=False,
                            label="",
                            widget=forms.TextInput(
                                attrs={"placeholder": "Search by "}))


class RealtorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Realtor
        fields = UserCreationForm.Meta.fields + (
            "rating",
            "first_name",
            "last_name",
        )


class RealtorUpdateForm(forms.ModelForm):
    class Meta:
        model = Realtor
        fields = ["rating"]


class RealtorUsernameSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by username"}))


class HouseSearchForm(forms.Form):
    price = forms.CharField(max_length=255,
                            required=False,
                            label="",
                            widget=forms.TextInput(
                                attrs={"placeholder": "Search by price"}))

estate/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RealtorCreationForm, RealtorUpdateForm, RealtorUsernameSearchForm, HouseSearchForm

from .models import (
    House,
    Realtor,
)


def index(request):
    num_houses = House.objects.count()
    num_realtors = Realtor.objects.count()

    context = {
        "num_houses": num_houses,
        "num_realtors": num_realtors,
    }

    return render(request, "estate/index.html", context=context)


class RealtorListView(generic.ListView):
    model = Realtor
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RealtorListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")

        context["search_form"] = RealtorUsernameSearchForm(
            initial={"username": username})
        return context

    def get_queryset(self):
        queryset = Realtor.objects.all()
        form = RealtorUsernameSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"])

        return super().get_queryset()


class RealtorDetailView(generic.DetailView):
    model = Realtor


class RealtorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Realtor
    fields = "__all__"
    form = RealtorCreationForm
    success_url = reverse_lazy("estate:realtor-list")


class RealtorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Realtor
    fields = "__all__"
    form = RealtorUpdateForm
    success_url = reverse_lazy("estate:realtor-list")


class RealtorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Realtor
    success_url = reverse_lazy("estate:realtor-list")
    queryset = Realtor.objects.all().prefetch_related("house")


class HouseListView(generic.ListView):
    model = House
    paginate_by = 3
    queryset = House.objects.all()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(HouseListView, self).get_context_data(**kwargs)

        price = self.request.GET.get("price", "")

        context["search_price_form"] = HouseSearchForm(
            initial={"price": price})
        return context

    def get_queryset(self):
        queryset = House.objects.all()
        form = HouseSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                price__icontains=form.cleaned_data["price"])

        return super().get_queryset()


class HouseDetailView(generic.DetailView):
    model = House


class HouseCreateView(LoginRequiredMixin, generic.CreateView):
    model = House
    fields = "__all__"
    success_url = reverse_lazy("estate:house-list")


class HouseUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = House
    fields = "__all__"
    success_url = reverse_lazy("estate:house-list")


class HouseDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = House
    success_url = reverse_lazy("estate:house-list")


class AssignToHouseView(LoginRequiredMixin, generic.View):
    model = House

    def post(self, request, pk) -> HttpResponseRedirect:
        house = get_object_or_404(House, pk=pk)
        if request.user in house.realtor.all():
            house.realtor.remove(request.user)
        else:
            house.realtor.add(request.user)
        return HttpResponseRedirect(
            reverse(
                "estate:house-detail", kwargs={"pk": pk}
            )
        )

templates/estate/house_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete house?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  <input type="submit" value="No" class="btn btn-success">
  </form>
{% endblock %}

templates/estate/house_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}

  <div class="container-fluid" >
  <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>

  </div>
  <div class="carousel-inner" style="height: 600px">
    <div class="carousel-item active carousel-img" >
      <img src="{% static "interior/1.jpg" %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static "interior/2.jpg" %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static "interior/3.jpg" %}" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
  </div>
   <h1>

     {% load humanize %}
     <p style="padding-top: 15px">{{ house.price|floatformat:0|intcomma }}$</p>

     <p style="font-size: 22px"><img src="{% static "ico/bed.png" %}" style="height: 20px;
    margin-right: 10px;
    width: 20px;">{{ house.num_of_bedrooms }} rooms</p>
    <span class="card-text" style="font-size: 22px"><img src="{% static "ico/area.png" %}" style="height: 25px;
    width: 25px;"> {{ house.area }} м²</span>
    <p style="font-size: 22px; padding-top: 10px">
      <img src="{% static "ico/floors.png" %}" style="height: 25px;
    width: 20px;">{{ house.num_of_floors }} storey house
    </p>
     <p style="padding-top: 10px">Description:</p>
     <p style="font-size: 14px">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin tristique, purus quis ultricies finibus, velit elit molestie augue, eu ultricies ante lectus eu orci. Pellentesque eget purus auctor, gravida ipsum eu, cursus ligula. Sed lacinia, eros lobortis maximus tristique, neque metus posuere nulla, nec dignissim nisi ligula eget libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Donec et dui ut quam tempor blandit. Aliquam commodo, ipsum eget facilisis maximus, dolor lacus fermentum mauris, nec euismod sem mi sit amet lectus. Vivamus pulvinar placerat suscipit.</p>
    <p>Location: <span style="font-size: 22px">{{ house.address }}</span></p>
     <p>Owner: <span style="font-size: 22px">{{ house.owner }}</span>
     <p>Phone number: <span style="font-size: 22px">+{{ house.owner.phone_number }}</span></p></p>

     <p>Realtors:
     {% if user.is_authenticated %}
     {% if house in user.house.all %}
       <form action="{% url 'estate:house-remove' house.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete me from this house</button>
      </form>
    {% else %}
      <form action="{% url 'estate:house-assign' house.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-success">Assign me to this house</button>
      </form>
    {% endif %}
      {% endif %}
     {% for realtor in house.realtor.all %}
        <hr>
        <p style="font-size: 24px"><strong>First name:</strong> {{ realtor.first_name }}</p>
        <p style="font-size: 24px"><strong>Last Name:</strong> {{ realtor.last_name }}</p>
       <p style="font-size: 24px"><strong>Rating:</strong> {{ realtor.rating }}⭐</p>
        <p class="text-muted" style="font-size: 24px"><strong>Id:</strong> {{realtor.id}}</p>
      <p><a href="{% url "estate:realtor-detail" pk=realtor.id %} " class="btn btn-dark" style="color: #fff;
    background-color: black;
    border-color: black; border-radius: 7px; padding: 10px">More details</a></p></p>
    {% empty %}
      <p>No realtors!</p>
    {% endfor %}



     <a href="{% url 'estate:house-delete' pk=house.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'estate:house-update' pk=house.id %}" class="btn btn-dark link-to-page" style="background-color: black">
      Update
    </a>
  </h1>
{% endblock %}

templates/estate/house_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} house</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-dark" style="background-color: black; bor">
  </form>
{% endblock %}

templates/estate/house_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <h1>
    Houses
    <a href="{% url 'estate:house-create' %}" class="btn btn-primary link-to-page" style="color: #fff;
    background-color: black;
    border-color: black; border-radius: 7px; padding-inline: 10px">
      Create
    </a>
  </h1>

  {% if house_list %}
<div class="wrapper" style="padding-bottom: 20px">
<div class="row">
      {% for house in house_list %}


<div class="card" style="width: 28rem; padding-top: 10px; padding-left: 5px" xmlns="http://www.w3.org/1999/html">

  <img src="{% static 'img/' %}{{ house.id }}.jpg" class="card-img-top" style="height: 80%">

  <div class="card-body">
    {% load humanize %}
    <div style="
    align-items: center;
    display: flex;
    justify-content: space-between;
    margin-bottom: 6px;
    position: relative;
    width: 75%;">
      <h5 class="card-title" style="
    font-size: 20px;
    font-weight: 650;
    line-height: 24px;">{{ house.price|floatformat:0|intcomma  }} $</h5>
    <h6 style="padding-left: 10px; color: #9396a8;font-size: 14px;
    font-weight: 400;
    line-height: 22px;
    overflow: hidden;
    padding-right: 34px;
    text-overflow: ellipsis;">{{ house.price_per_area }}$ for м²</h6>
      </div>
    <p class="card-text">{{ house.address }} </p>

    <span><img src="{% static "ico/bed.png" %}" style="height: 20px;
    margin-right: 10px;
    width: 20px;">{{ house.num_of_bedrooms }} rooms</span>
    <span class="card-text"><img src="{% static "ico/area.png" %}" style="height: 25px;
    width: 25px;"> {{ house.area }} м²</span>
    <br>
      <img src="{% static "ico/floors.png" %}" style="height: 25px;
    width: 20px;">{{ house.num_of_floors }} storey house
    </br>
    <p>
    <a href="{% url "estate:house-detail" pk=house.id %} " class="btn btn-dark" style="color: #fff;
    background-color: black;
    border-color: black; border-radius: 7px; padding: 10px">More details</a></p>
  </div>
</div>





      {% endfor %}
</div>
    </div>
  {% else %}
    <p>There are no houses in Data Base</p>
  {% endif %}

{% endblock %}

templates/estate/index.html
{% extends "base.html" %}

{% block content %}

    <h1>Real Estate Home Page</h1>
    <p>Welcome to Best Real Estate Data Base!</p>
    <h2>The service has the following record counts:</h2>
    <ul>
        <li><strong>Houses:</strong> {{ num_houses }}</li>
        <li><strong>Realtors:</strong> {{ num_realtors }}</li>
    </ul>
  <p style="font-size: 24px">Discover the essence of exquisite living through our curated selection of premium properties. As the premier destination for those seeking unparalleled elegance and luxury, our portfolio showcases an array of homes meticulously crafted to exceed every expectation.</p>


{% endblock %}

templates/estate/realtor_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    <p style="font-size: 24px"><span>First name:</span> {{ realtor.first_name }}</p>
  <p style="font-size: 24px"><span>Last name:</span> {{ realtor.last_name }}</p>
  <p style="font-size: 24px"><span>Rating: </span>{{ realtor.rating }} ⭐</p>
    <div class="ml-3">
    <h4>Houses:</h4>

    {% for house in realtor.house.all %}
        <hr>
        <p style="font-size: 24px"><strong>Address:</strong> {{ house.address }}</p>
        <p style="font-size: 24px"><strong>Price:</strong> {{ house.price }}</p>
        <p class="text-muted" style="font-size: 24px"><strong>Id:</strong> {{house.id}}</p>
      <p><a href="{% url "estate:house-detail" pk=house.id %} " class="btn btn-dark" style="color: #fff;
    background-color: black;
    border-color: black; border-radius: 7px; padding: 10px">More details</a></p>

    {% empty %}
      <p>No houses!</p>
    {% endfor %}
  </div>
    <a href="{% url 'estate:realtor-delete' pk=realtor.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'estate:realtor-update' pk=realtor.id %}" class="btn btn-secondary link-to-page">
      Update
    </a>
  </h1>
{% endblock %}

templates/estate/realtor_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} realtor</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-dark" style="background-color: black; bor">
  </form>
{% endblock %}

templates/estate/realtor_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
  <h1>
    Realtors
    <a href="{% url 'estate:realtor-create' %}" class="btn btn-primary link-to-page" style="color: #fff;
    background-color: black;
    border-color: black; border-radius: 7px; padding-inline: 10px">
      Create
    </a>
  </h1>

  {% if realtor_list %}
<div class="wrapper" style="padding-bottom: 20px">
<div class="row">
      {% for realtor in realtor_list %}


<div class="card" style="width: 28rem; padding-top: 10px; padding-left: 5px" xmlns="http://www.w3.org/1999/html">

  <div class="card-body">
<p style="font-size: 24px"> {{ realtor.first_name }} {{ realtor.last_name }}</p>
  <p style="font-size: 24px">{{ realtor.rating }} ⭐</p>
    <p style="font-size: 24px">{{ realtor.house.all.count }} houses at sale</p>
    <p>
    <a href="{% url "estate:realtor-detail" pk=realtor.id %} " class="btn btn-dark" style="color: #fff;
    background-color: black;
    border-color: black; border-radius: 7px; padding: 10px">More details</a></p>
  </div>
</div>





      {% endfor %}
</div>
    </div>
  {% else %}
    <p>There are no realtors in Data Base</p>
  {% endif %}

{% endblock %}